# Default configuration for DocGenAI

# AI model settings
model:
  # The name of the Hugging Face model to use.
  name: "Gen-Verse/MMaDA-8B-Base"
  # Note: Set your Hugging Face token via the HUGGING_FACE_TOKEN environment variable
  # Do not put tokens in this config file as they may be accidentally committed to git

  # Quantization options: "none", "8bit", "4bit"
  # 8bit: 2x faster loading, ~95-98% quality (recommended)
  # 4bit: 4x faster loading, ~90-95% quality
  # none: Full precision, slower loading, best quality
  quantization: "4bit"

  # Keep model in memory between files (faster for multiple files)
  session_cache: true

# Caching settings
cache:
  # Enable all caching features
  enabled: true

  # Cache generation results to avoid re-generating for same content
  generation_cache: true

  # Directory to store cache files
  cache_dir: ".cache/docgenai"

  # Maximum cache size in MB (old entries deleted when exceeded)
  max_cache_size_mb: 1000

# Output settings
output:
  # The directory where generated documentation will be saved.
  dir: "output"
  # The default filename for the generated markdown file.
  filename_template: "{original_filename}_docs.md"

# Template settings
templates:
  # Path to the directory containing documentation templates.
  dir: "src/docgenai/templates"
  # The default template to use for generating documentation.
  doc_template: "default_doc_template.md"
  # A style guide to be injected into the AI prompt.
  style_guide: "default_style_guide.md"
