[tool.poetry]
name = "docgenai"
version = "0.1.0"
description = "AI-powered documentation and diagramming tool."
authors = ["AI Assistant <assistant@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.1.7"
transformers = "4.36.2"
torch = "2.1.2"
jinja2 = "^3.1.2"
Pillow = "^10.2.0"
python-dotenv = "^1.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pre-commit = "^3.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
docgenai = "docgenai.cli:cli"
