name: Renovate

on:
  # Run weekly on Mondays at 9:00 AM UTC
  schedule:
    - cron: '0 9 * * 1'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.3.2
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          # Optional: Enable debug logging
          LOG_LEVEL: info
